CoinHologram: "&x&F&D&F&5&E&6{coin}&x&D&A&A&5&2&0$"
CoinActionBar: "&x&D&C&D&C&D&C生物击杀!   &x&F&D&F&5&E&6+ {coin}&x&D&A&A&5&2&0⛁"
CoinFull: "&x&D&C&D&C&D&C生物击杀!   &c今日已达上限"
DailyMax: 10000.0

BlackItems:
  - BOW
  - CROSSBOW
  - TRIDENT
  - SNOWBALL
  - ENDER_PEARL
  - FISHING_ROD

BlackSkillsWorld:
  - "Lobby"
  - "VoidWorld"

Board:
  prefix: "&8[&x&8&E&8&E&8&E报纸&8] "
  messages:
    - "The One"

text: '<font:nameplates:default>%nameplates_bg_pos%</font>%img_bar_compass%  <font:nameplates:offset_3><color:#BC8F8F>%player_x%, %player_y%, %player_z%</color>   </font><font:nameplates:default>%nameplates_bg_inv%</font>%img_bar_chest_minecart% <font:nameplates:offset_3><color:#DEB887>%player_empty_slots%</color></font>   <font:nameplates:default>%nameplates_bg_time%</font>%img_bar_clock% <font:nameplates:offset_3><color:#FFE4C4>%player_world_time_24%</color></font>'
color: WHITE
refresh-rate: 10
overlay: NOTCHED_20