name: MoonCube
version: ${project.version}
api-version: 1.18
main: me.xiaozhangup.mooncube.MoonCube
depend:
  - Vault
  - PlaceholderAPI
  - IridiumSkyblock
  - TAB
commands:
  mooncube:
    description: MoonCube Main Command
    aliases:
      - moonc
  profile:
    description: Edit your profile
    aliases:
      - pfe
  tabc:
    description: Tab Settings
  menu:
    description: Menu
authors:
  - xiaozhangup