name: MoonCube
version: ${project.version}
api-version: 1.18
main: me.xiaozhangup.mooncube.MoonCube
depend:
  - Vault
  - PlaceholderAPI
  - IridiumSkyblock
  - TAB
  - AureliumSkills
  - ProtocolLib
  - ItemsAdder
commands:
  mooncube:
    description: MoonCube Main Command
    aliases:
      - moonc
  profile:
    description: Edit your profile
    aliases:
      - pfe
  tabc:
    description: Tab Settings
  menu:
    description: Menu
  unique:
    description: Unique shop
  holoclear:
    description: Clear holo text
  iaguide:
    description: Get ia guide book
  moonitem:
    description: MoonCube NBT Saver
  arcaneavl:
    description: Arcane anvil
  arcanebk:
    description: Arcane book
authors:
  - xiaozhangup