name: MoonCube
version: ${project.version}
api-version: 1.18
main: me.xiaozhangup.mooncube.MoonCube
depend:
  - Vault
  - PlaceholderAPI
  - IridiumSkyblock
  - TAB
  - ProtocolLib
  - ItemsAdder
  - MinePay
  - Nova
  - Essentials
  - AdvancedChests

commands:
  mooncube:
    description: MoonCube Main Command
    aliases:
      - moonc
  profile:
    description: Edit your profile
    aliases:
      - pfe
  tabc:
    description: Tab Settings
  menu:
    aliases:
      - cd
      - mc
    description: Menu
  unique:
    description: Unique shop
  holoclear:
    description: Clear holo text
  iaguide:
    description: Get ia guide book
  moonitem:
    description: MoonCube NBT Saver
  arcaneavl:
    description: Arcane anvil
  arcanebk:
    description: Arcane book
  actionblockadd:
    description: Add ActionBlock
  actionblockremove:
    description: Remove ActionBlock
  treepicker:
    description: Open PickTree GUI
  spawn:
  setspawn:
authors:
  - xiaozhangup